// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dadaxiaoxiao/web-bff/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *WebApp {
	client := ioc.InitEtcdClient()
	cmdable := ioc.InitRedis()
	cronJobServiceClient := ioc.InitCronJobGRPCClient(client, cmdable)
	localFuncExecutor := ioc.InitLocalFuncExecutor()
	httpExecutor := ioc.InitHttpExecutor()
	logger := ioc.InitLogger()
	scheduler := ioc.InitScheduler(cronJobServiceClient, localFuncExecutor, httpExecutor, logger)
	webApp := &WebApp{
		Scheduler: scheduler,
	}
	return webApp
}

// wire.go:

var thirdPartyProvider = wire.NewSet(ioc.InitLogger, ioc.InitRedis, ioc.InitOTEL, ioc.InitEtcdClient)

var cronjobProvider = wire.NewSet(ioc.InitCronJobGRPCClient, ioc.InitHttpExecutor, ioc.InitLocalFuncExecutor, ioc.InitScheduler)
